### ISSUE TITLE
現時PIXIV小説摘取不能，而另外兩站倒是可以

### ISSUE THREAD

**Issue by CNrocke** [chrisliuqq/PIBBK-Lite#9]
(3) ["parseChapterTitle", Array(2), "<!DOCTYPE html>↵<html lang="zh-CN"xmlns:wb="http:/…77be5,0x2df056895d],}})();</script></body></html>"]
app.js:26877 [Vue warn]: Error in v-on handler (Promise/async): "TypeError: Cannot use 'in' operator to search for '1' in null"

(found in <Root>)
warn @ app.js:26877
logError @ app.js:28140
globalHandleError @ app.js:28135
handleError @ app.js:28095
(anonymous) @ app.js:28112
Promise.catch (async)
invokeWithErrorHandling @ app.js:28112
invoker @ app.js:28435
original._wrapper @ app.js:33797
app.js:28144 TypeError: Cannot use 'in' operator to search for '1' in null
    at PixivParser.parseContent (app.js:38524)
    at Vue.eventFetchButtonClick (app.js:38873)

**Comment by chrisliuqq** [comment]
https://github.com/chrisliuqq/PIBBK-Lite/releases/tag/v1.4.2

新版本修正了這個問題，可重新下載～

**Comment by CNrocke** [comment]
thx❤

**Comment by chrisliuqq** [comment]
看起來正常了，關掉 issue 了。
